#define SLIZZEEP 250000000	/*	THIS VALUE REFERS TO THE SPACING BETWEEN INTRA-CHARACTER WORD, E.G., "LATIN" AND "MINUSCULE".	*/

float vaaa[] = 
{
	1,					/*	THIS VALUE REFERS TO THE DELAY WHICH IS PLACED BETWEEN CHARACTERS.	*/
	1,					/*	THE SPEED OF THE ANNOUNCEMENT IS MULTIPLIED BY THIS VALUE.  AS OF WRITING THIS COMMENT, THIS VALUE IS NOT USED.	*/
};
