float vaaa[] = 
{
	1,					/*	THIS VALUE REFERS TO THE DELAY WHICH IS PLACED BETWEEN CHARACTERS.	*/
	1,					/*	THE SPEED OF THE ANNOUNCEMENT IS MULTIPLIED BY THIS VALUE.	*/
	0.25				/*	THIS VALUE REFERS TO THE SPACING BETWEEN INTRA-CHARACTER WORD, E.G., "LATIN" AND "MINUSCULE".*/
};
