.TH evncr 1
.SH NAME
evncr - read stdin in the voice of EVAN DOORBELL <www.evan-doorbell.com>
.SH DESCRIPTION
EVANNOUNCER (\fBevncr\fR) is a computer program which was created by VARIK VALEFOR and EVAN DOORBELL with the intent of creating a program which is capable of very clearly reading the program's input to the program's user.

\fBevncr\fR can be used to read passwords, UIDs, or essentially any form of text data which is of a reasonable length.
.SH EXAMPLE
\fBecho asshat | evncr\fR should make the terminal speaker output "LATIN MINUSCULE ALFA, LATIN MINUSCULE SIERRA, LATIN MINUSCULE SIERRA, LATIN MINUSCULE HOTEL, LATIN MINUSCULE ALFA, LATIN MINUSCULE TANGO".
.SH OPTIONS
\fB-d([0-9]+)\fR - enables variable \fB\\1\fR.  The meanings of the various debugging variables are visible in the comments of \fBv__d.h\fR.

\fB-x\fR disables reading the prefixes, e.g., "MAJUSCULE".
.SH NOTES
-\fBevncr\fR currently lacks support for non-OpenBSD operating systems.  This problem shall eventually be solved if a want for a cross-platform \fBevncr\fR is voiced by \fBevncr\fR's potential users.
.SH FILES
The \fBsounds\fR directory contains the audio files which are played by \fBevncr\fR when reading sequences.  With the exception of \fBevncr\fR-specific pseudocharacters, e.g., "LATIN" and "MINUSCULE", for all printable ASCII characters, the \fBevncr\fR which contains this character is named \fB[ASCII integer representation of character].wav\fR.  See \fBfred.h\fR for more details.
.SH CONTACT
VARIK VALEFOR, the author of this source code, can be contacted at \fB varikvalefor@aol.com\fR.
