.Dd $Mdocdate$
.Dt evncr 1
.Os

.Sh NAME
.Nm evncr
.Nd read stdin in the voice of EVAN DOORBELL

.Sh SYNOPSIS
.Nm evncr

.Sh DESCRIPTION
EVANNOUNCER 
.Pp .Nm
is a UNIX philosophy-compliant computer program which was created by VARIK VALEFOR and EVAN DOORBELL with the intent of creating a program which is capable of very clearly -- and enjoyably --  reading the program's input to the program's user.

.Nm
can be used to read passwords, UIDs, or essentially any form of text data which is of a reasonable length.

.Sh EXAMPLE
Running
.Sy echo asshat | evncr
should make the terminal speaker output
.Qq LATIN MINUSCULE ALFA, LATIN MINUSCULE SIERRA, LATIN MINUSCULE SIERRA, LATIN MINUSCULE HOTEL, LATIN MINUSCULE ALFA, LATIN MINUSCULE TANGO
in the voice of EVAN DOORBELL.

.Sh FILES
The
.Pa sounds
directory contains the audio files which are played by
.Nm
when reading sequences.  With the exception of pseudocharacters which are unique to
.Nm ,
e.g.,
.Qq LATIN
and
.Qq MINUSCULE ,
for all printable ASCII characters, the file which contains this character is named
.Sy [ASCII integer representation of character].wav .
However, majuscule and minuscule characters share source files, with the phrases
.Qq MAJUSCULE
and
.Qq MINUSCULE
being stored in individual files.  By using this approach, a few bytes can be saved.
The specifics of the conversion process can be gleaned from the functions which are called by
.Va thingToInt .

On UNIX-based systems, the
.Pa sounds
folder is located in
.Pa /usr/local/share/evncr/ ,
and on Windows systems, the
.Pa sounds
folder is located in
.Pa [host drive]:\\\\Program Files\\\\EVANNOUNCER\\\\.

.Sh DIAGNOSTICS
.Qq What is your major malfunction, numbnuts?
is output when the user has input a bad option.

.Sh NOTES
As a result of using
.Sy mplayer
as the method of playing sounds, a functional
.Sy mplayer
installation is required.

EVAN's voice samples have not yet been provided.

Support for different inflections has not yet been implemented.

The current cross-platform solution for
.Nm
does not yet support all modern operating systems.

.Sh HISTORY
The development of the first version of
.Nm
began on 20200709 and lasted two (2) days; the source code of this version of the program was terribly messy, and the
.Qq code smell
sucked.  The Git commit which marked the creation of a new version read
.Qq [t]o hell with this.  A new version is in order.

The previous version of
.Nm
is written in C++ and is a bit unwieldy.

This version of
.Nm
is written in Haskell and was created because functionality could not be added to the previous version of
.Nm .

.Sh CONTACT
Hate mail regarding
.Nm
can be sent to VARIK
.Qq NOT A COMPUTER PROGRAMMER!
VALEFOR
.Aq varikvalefor@aol.com ,
.Em not
to EVAN DOORBELL or Mr. REID; of these individuals, the former only supplied the audio recordings and is the basis of the mascot, and the latter is completely unaffiliated with the project.
