#define SLIZZEEP1	0	/*	THIS VALUE CONTAINS THE NUMBER OF SECONDS WHICH SHOULD OCCUR BETWEEN INTRA-CHARACTER WORDS.	*/
#define SLIZZEEP	250000000	/*	THIS VALUE REFERS TO THE NANOSECOND SPACING BETWEEN INTRA-CHARACTER WORD, E.G., "LATIN" AND "MINUSCULE".	*/
#define SLIZZLE1	1	/*	THIS VALUE REFERS TO THE SECOND SPACING BETWEEN CHARACTERS.	*/
#define SLIZZLE	0	/*	THIS VALUE REFERS TO THE NANOSECOND SPACING BETWEEN CHARACTERS.	*/
#define SLIZZY1 2
#define SLIZZY 0



float vaaa[] = 
{
	1,					/*	THE SPEED OF THE ANNOUNCEMENT IS MULTIPLIED BY THIS VALUE.  AS OF WRITING THIS COMMENT, THIS VALUE IS NOT USED.	*/
};

